### ISSUE TITLE
not uplloading correctly?

### ISSUE THREAD

**Issue by cyndernight** [DarkWanderer/Elite-Log-Agent#52] opened 2018-10-30 23:33 UTC
hi,  seams the log agent isn't uploading correctly...

its not sending my data to inara.

i put in a inara API key thing, and i play ED and its not uploading my system or material changes...

i do something wrong?

**Comment by DarkWanderer** [comment] 2018-10-31 19:40
Hi! Let's see what might have gone wrong.

Have you clicked "Validate" after inputting your INARA key?
![screenshot1](https://cdn.discordapp.com/attachments/448396053629239296/470148416408649738/unknown.png)
The API key field must start glowing green after that (like on screenshot) and the checkbox must be ticked.

After you made sure it's green and the 'validated' checkbox is ticked (it ticks automatically if API key is correct), **please make sure to save the settings** (press OK). Then, open the settings again and press "upload latest 5 files" on "General" tab
![screenshot2](https://media.discordapp.net/attachments/448396053629239296/470148331138449438/unknown.png)
After waiting for 10-20 seconds, open INARA and check if that helped

If that does not work, please send me ELA log. It is located in `%appdata%\EliteLogAgent\Log` (you can copy-paste that string into explorer) and I'll take a closer look

**Comment by cyndernight** [comment] 2018-11-01 05:52
I did use the api
It uploads “intermittently”

So not every jump, not every station landing, it can be more then 10 jumps before it “ticks” and uploads... 

Normally not a problem unless I’m doing engineering and need the materials to update while I’m in planet and it won’t do it

So, it’s “kinda” working

**Comment by DarkWanderer** [comment] 2018-11-01 06:41
That sounds strange. if it works, it must upload INARA data every 30 seconds. 

Can you attach a few logs as per my comment above?

**Comment by DarkWanderer** [comment] 2018-11-01 17:11
I think I start to understand what the issue is. Are your materials spent on engineering not updated, until some time after?

**Comment by DarkWanderer** [comment] 2018-12-18 07:07
Closing as the issue is probably resolved by now

**Closed by DarkWanderer** 2018-12-18 07:07 UTC
